<?php

namespace AppBundle\Repository;

/**
 * AuthorPostDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorPostDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
