services:
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    author_form_factory:
        class: AppBundle\Service\PostFormFactory
        arguments: [ "@router", "@form.factory", AppBundle\Form\AuthorPostType, 'author' ]

    regular_form_factory:
        class: AppBundle\Service\PostFormFactory
        arguments: [ "@router", "@form.factory", AppBundle\Form\RegularPostType, 'regular' ]
